services:
  - type: web
    name: api
    env: docker
    plan: free
    envVars:
      - fromGroup: finalproject
      - key: DATABASE_URL
        fromDatabase:
          name: clothingstore
          property: connectionString

databases:
  - name: clothingstore
    plan: free